services:
  libraryApi:
    build: 
      context: .
    ports:
      - "${API_PORT}:3000"
    env_file:
      - .env.docker
    volumes:
      - ./:/app
    depends_on:
      - db
    command: ["sh", "-c", "npm start"]

  db:
    image: mysql:8.0
    container_name: mysql_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
