version: '3.8'

services:
  libraryapi:
    container_name: libraryapigrp07
    build:
      context: ./libraryapi
    ports:
      - "3000:3000"
    volumes:
      - ./libraryapi:/app
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASS=root
      - DB_NAME=libraryapi

  libraryweb:
    container_name: librarywebgrp07
    build:
      context: ./libraryweb
    ports:
      - "3001:3000"
    depends_on:
      - libraryapi

  db:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=maiconkuster
      - MYSQL_DATABASE=libraryapi
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  db-data: